// Source URLs are agency or program pages. No changing income threshold is asserted in seed rules.
const today = new Date().toISOString().slice(0, 10);
const item = (id, name, organization, categories, en, es, whoEn, whoEs, url, extra = {}) => ({
  id, name, organization, categories, description_en: en, description_es: es,
  eligibility_summary_en: whoEn, eligibility_summary_es: whoEs,
  eligibility_rules: {}, documents_needed: [], how_to_apply: '', apply_url: url,
  phone: '', address: '', hours: '', coverage_type: 'national', coverage_state: '',
  coverage_zip_codes: [], is_active: true, last_verified_date: today, source_url: url,
  priority_weight: 0, ...extra
});
const tx = { coverage_type: 'state', coverage_state: 'TX' };
const austin = { coverage_type: 'zip_list', coverage_zip_codes: Array.from({length: 200}, (_, i) => String(78600 + i)).concat(Array.from({length: 200}, (_, i) => String(78700 + i))) };
export const seedResources = [
  item('snap','SNAP food benefits','USDA', ['food'], 'Monthly help buying groceries.', 'Ayuda mensual para comprar alimentos.', 'Households with limited income; the state decides.', 'Hogares con ingresos limitados; el estado decide.', 'https://www.fns.usda.gov/snap/recipient/eligibility', {documents_needed:['Proof of income','Photo ID','Proof of address'], priority_weight: 4}),
  item('wic','WIC','USDA', ['food','healthcare'], 'Food, nutrition advice, and referrals for pregnant people and young children.', 'Alimentos, orientación nutricional y referencias para embarazadas y niños pequeños.', 'Pregnant or postpartum people, infants, and children under 5.', 'Embarazadas, personas después del parto, bebés y niños menores de 5 años.', 'https://www.fns.usda.gov/wic', {eligibility_rules:{requires_child_under_5_or_pregnant:true}, documents_needed:['Proof of income','Proof of address'], priority_weight: 3}),
  item('school_meals','School meals','USDA', ['food','school_childcare'], 'Free or reduced-price breakfast and lunch through participating schools.', 'Desayuno y almuerzo gratis o a precio reducido en escuelas participantes.', 'School-age children; ask the school about its process.', 'Niños en edad escolar; consulte el proceso de la escuela.', 'https://www.fns.usda.gov/school-meals', {eligibility_rules:{requires_children:true}, priority_weight: 2}),
  item('medicaid','Medicaid','Centers for Medicare & Medicaid Services', ['healthcare'], 'Low-cost or free health coverage administered by each state.', 'Cobertura médica gratuita o de bajo costo administrada por cada estado.', 'Rules vary by state, income, age, and household.', 'Las reglas varían según el estado, ingresos, edad y hogar.', 'https://www.medicaid.gov/medicaid/eligibility/index.html', {documents_needed:['Proof of income','Photo ID'], priority_weight: 3}),
  item('chip','CHIP','Centers for Medicare & Medicaid Services', ['healthcare'], 'Health coverage for children whose families may not qualify for Medicaid.', 'Cobertura médica para niños cuyas familias quizá no reciban Medicaid.', 'Uninsured children; state rules apply.', 'Niños sin seguro; se aplican reglas estatales.', 'https://www.insurekidsnow.gov/', {eligibility_rules:{requires_children:true}, documents_needed:['Proof of income'], priority_weight: 2}),
  item('liheap','LIHEAP','U.S. Department of Health and Human Services', ['utilities'], 'Help with home heating and cooling costs through local agencies.', 'Ayuda con costos de calefacción y aire acondicionado por agencias locales.', 'Households with limited income; funds and rules vary locally.', 'Hogares con ingresos limitados; fondos y reglas varían localmente.', 'https://www.acf.hhs.gov/ocs/programs/liheap', {documents_needed:['Utility bill','Proof of income'], priority_weight: 2}),
  item('lifeline','Lifeline','Federal Communications Commission', ['utilities'], 'A monthly discount on qualifying phone or internet service.', 'Descuento mensual para servicio de teléfono o internet que cumpla los requisitos.', 'People meeting income or program participation rules.', 'Personas que cumplen reglas de ingresos o participación en programas.', 'https://www.lifelinesupport.org/', {priority_weight: 1}),
  item('head_start','Head Start','U.S. Department of Health and Human Services', ['school_childcare'], 'Early learning and family support for young children.', 'Educación temprana y apoyo familiar para niños pequeños.', 'Families with young children; local programs decide enrollment.', 'Familias con niños pequeños; cada programa decide la inscripción.', 'https://www.acf.hhs.gov/ohs', {eligibility_rules:{requires_child_under_5:true}, priority_weight: 2}),
  item('unemployment','Unemployment insurance','U.S. Department of Labor', ['employment','cash_assistance'], 'Temporary income support after qualifying job loss.', 'Apoyo temporal de ingresos después de perder un empleo que cumple los requisitos.', 'Workers with qualifying wages and job separation; apply in your state.', 'Trabajadores con salarios y separación laboral que cumplen las reglas; solicite en su estado.', 'https://www.dol.gov/general/topic/unemployment-insurance', {priority_weight: 2}),
  item('hud_counseling','HUD housing counseling','HUD', ['housing','legal'], 'Talk with a housing counselor about rent, eviction, or other housing concerns.', 'Hable con un asesor sobre alquiler, desalojo u otras inquietudes de vivienda.', 'People seeking housing guidance.', 'Personas que buscan orientación sobre vivienda.', 'https://www.hud.gov/hud-partners/single-family-about-housing-counseling', {phone:'800-569-4287', priority_weight: 2}),
  item('findhelp','Findhelp','Findhelp', ['food','housing','utilities','healthcare','school_childcare','employment','transportation','cash_assistance','legal','mental_health'], 'Search for nearby community support by ZIP code.', 'Busque apoyo comunitario cercano con su código postal.', 'Anyone looking for local services.', 'Cualquier persona que busque servicios locales.', 'https://www.findhelp.org/', {priority_weight: -20}),
  item('211','211 local help','United Way', ['food','housing','utilities','healthcare','school_childcare','employment','transportation','cash_assistance','legal','mental_health'], 'A local specialist can help you find nearby services and next steps.', 'Un especialista local puede ayudarle a encontrar servicios y próximos pasos.', 'Anyone in the United States seeking community help.', 'Cualquier persona en Estados Unidos que busque ayuda comunitaria.', 'https://211.org/', {phone:'211', priority_weight: 0}),
  item('988','988 Suicide & Crisis Lifeline','988 Lifeline', ['mental_health'], 'Free crisis support by call or text, any time.', 'Apoyo gratuito en crisis por llamada o texto, en cualquier momento.', 'Anyone in emotional distress or worried about someone else.', 'Cualquier persona en crisis emocional o preocupada por alguien.', 'https://988lifeline.org/', {phone:'988', hours:'24/7', priority_weight: 5}),
  item('yourtexasbenefits','Your Texas Benefits','Texas Health and Human Services', ['food','healthcare','cash_assistance'], 'Texas portal to apply for SNAP, Medicaid, CHIP, and cash help.', 'Portal de Texas para solicitar SNAP, Medicaid, CHIP y ayuda en efectivo.', 'Texas residents; each program makes its own decision.', 'Residentes de Texas; cada programa toma su propia decisión.', 'https://www.yourtexasbenefits.com/', {...tx, documents_needed:['Proof of income','Photo ID','Proof of address'], priority_weight: 4}),
  item('twc','Texas unemployment benefits','Texas Workforce Commission', ['employment','cash_assistance'], 'Apply for Texas unemployment benefits and see job-search guidance.', 'Solicite beneficios de desempleo de Texas y orientación laboral.', 'Texas workers who lost work or had hours reduced; TWC decides.', 'Trabajadores de Texas que perdieron empleo o horas; TWC decide.', 'https://www.twc.texas.gov/programs/unemployment-benefits', {...tx, priority_weight: 3}),
  item('ctfb','Central Texas Food Bank','Central Texas Food Bank', ['food'], 'Find a nearby food pantry or food distribution.', 'Encuentre una despensa o distribución de alimentos cercana.', 'People needing food in Central Texas.', 'Personas que necesitan alimentos en el centro de Texas.', 'https://www.centraltexasfoodbank.org/find-food-now', {...austin, priority_weight: 10}),
  item('austin_energy','Austin Energy customer assistance','City of Austin Utilities', ['utilities'], 'Programs that may help City of Austin utility customers with bills.', 'Programas que pueden ayudar a clientes de servicios públicos de la Ciudad de Austin con sus facturas.', 'City of Austin utility customers; check current program rules.', 'Clientes de servicios públicos de la Ciudad de Austin; confirme las reglas actuales.', 'https://coautilities.com/wps/wcm/connect/occ/coa/util/support/customer-assistance', {...austin, phone:'512-494-9400', documents_needed:['Utility bill','Proof of income'], priority_weight: 10}),
  item('ceap','Texas Comprehensive Energy Assistance Program','Texas Department of Housing and Community Affairs', ['utilities'], 'Local agencies may help pay energy bills and address urgent energy needs.', 'Agencias locales pueden ayudar a pagar energía y resolver necesidades urgentes.', 'Texas households with limited income; local agency decides.', 'Hogares de Texas con ingresos limitados; decide la agencia local.', 'https://www.tdhca.texas.gov/comprehensive-energy-assistance-program-ceap', {...tx, documents_needed:['Utility bill','Proof of income'], priority_weight: 3}),
  item('wfsca','Workforce Solutions Capital Area','Workforce Solutions Capital Area', ['employment','school_childcare'], 'Job-search and training support; ask about child care services.', 'Apoyo para buscar trabajo y capacitación; pregunte por cuidado infantil.', 'People in the Austin area looking for work or training.', 'Personas en Austin que buscan trabajo o capacitación.', 'https://www.wfscapitalarea.com/', {...austin, priority_weight: 3}),
  item('capmetro','CapMetro reduced fares','CapMetro', ['transportation'], 'Reduced transit fares for riders who meet current criteria.', 'Tarifas de transporte reducidas para pasajeros que cumplen los criterios actuales.', 'Riders in the CapMetro service area; verify current fare rules.', 'Pasajeros del área de CapMetro; confirme reglas actuales.', 'https://www.capmetro.org/fares', {...austin, priority_weight: 2}),
  item('aisd_meals','Austin ISD school meals','Austin Independent School District', ['food','school_childcare'], 'Check school breakfast and lunch options for Austin ISD students.', 'Consulte opciones de desayuno y almuerzo para estudiantes de Austin ISD.', 'Students attending Austin ISD schools.', 'Estudiantes de escuelas de Austin ISD.', 'https://www.austinisd.org/nutrition-food-services', {...austin, eligibility_rules:{requires_children:true}, priority_weight: 2})
];
