/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['"Bricolage Grotesque"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        hand: ['Caveat', '"Comic Sans MS"', 'cursive'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))', soft: 'hsl(var(--primary-soft))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))', soft: 'hsl(var(--accent-soft))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        danger: { DEFAULT: 'hsl(var(--danger))', foreground: 'hsl(var(--danger-foreground))', soft: 'hsl(var(--danger-soft))' },
        success: { DEFAULT: 'hsl(var(--success))', soft: 'hsl(var(--success-soft))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      boxShadow: {
        soft: '0 1px 2px rgb(15 23 42 / 0.04), 0 4px 16px rgb(15 23 42 / 0.06)',
        lift: '0 2px 4px rgb(15 23 42 / 0.06), 0 12px 32px rgb(15 23 42 / 0.10)',
      },
      keyframes: {
        'fade-up': { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'none' } },
        pop: { '0%': { transform: 'scale(0.6)' }, '60%': { transform: 'scale(1.15)' }, '100%': { transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-400px 0' }, to: { backgroundPosition: '400px 0' } },
        float: { '0%,100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-10px) rotate(3deg)' } },
        wiggle: { '0%,100%': { transform: 'rotate(-3deg)' }, '50%': { transform: 'rotate(3deg)' } },
        jelly: { '0%,100%': { transform: 'scale(1,1)' }, '30%': { transform: 'scale(1.12,0.9)' }, '50%': { transform: 'scale(0.92,1.08)' }, '70%': { transform: 'scale(1.04,0.97)' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        morph: { '0%,100%': { borderRadius: '42% 58% 63% 37% / 41% 44% 56% 59%' }, '33%': { borderRadius: '70% 30% 46% 54% / 30% 29% 71% 70%' }, '66%': { borderRadius: '31% 69% 36% 64% / 58% 61% 39% 42%' } },
        drift: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '33%': { transform: 'translate(30px,-40px) scale(1.1)' }, '66%': { transform: 'translate(-25px,20px) scale(0.95)' } },
        'bounce-in': { '0%': { opacity: 0, transform: 'scale(0.6) rotate(-6deg)' }, '60%': { opacity: 1, transform: 'scale(1.06) rotate(2deg)' }, '100%': { transform: 'scale(1) rotate(0)' } },
      },
      animation: {
        'fade-up': 'fade-up 0.35s ease-out both',
        pop: 'pop 0.3s ease-out',
        shimmer: 'shimmer 1.4s linear infinite',
        float: 'float 6s ease-in-out infinite',
        wiggle: 'wiggle 0.6s ease-in-out',
        'wiggle-slow': 'wiggle 3s ease-in-out infinite',
        jelly: 'jelly 0.6s ease-in-out',
        marquee: 'marquee 40s linear infinite',
        morph: 'morph 12s ease-in-out infinite',
        drift: 'drift 18s ease-in-out infinite',
        'bounce-in': 'bounce-in 0.55s cubic-bezier(.2,.9,.3,1.3) both',
      },
    },
  },
  plugins: [],
};
