/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Rethink Sans"', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        display: ['"Bricolage Grotesque"', '"Rethink Sans"', 'ui-sans-serif', 'sans-serif'],
        hand: ['"Gochi Hand"', 'cursive'],
        mono: ['"Space Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))', soft: 'hsl(var(--primary-soft))', deep: 'hsl(var(--primary-deep))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))', soft: 'hsl(var(--accent-soft))', deep: 'hsl(var(--accent-deep))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        danger: { DEFAULT: 'hsl(var(--danger))', foreground: 'hsl(var(--danger-foreground))', soft: 'hsl(var(--danger-soft))' },
        success: { DEFAULT: 'hsl(var(--success))', soft: 'hsl(var(--success-soft))' },
        ink: 'hsl(var(--ink))',
        paper: { DEFAULT: 'hsl(var(--background))', 2: 'hsl(var(--paper-2))' },
        sun: { DEFAULT: 'hsl(var(--sun))', deep: 'hsl(var(--sun-deep))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      boxShadow: {
        // Hard offset 'ink' shadows only — no blur anywhere (see docs/DESIGN.md).
        soft: '0 1px 0 hsl(var(--ink) / 0.05), 0 12px 24px -18px hsl(var(--ink) / 0.45)',
        lift: '0 2px 0 hsl(var(--ink) / 0.06), 0 18px 30px -18px hsl(var(--ink) / 0.5)',
        ink: '4px 4px 0 hsl(var(--ink))',
        'ink-sm': '3px 3px 0 hsl(var(--ink))',
        'ink-lg': '6px 6px 0 hsl(var(--ink))',
        press: '0 4px 0 hsl(var(--ink))',
      },
      keyframes: {
        'fade-up': { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'none' } },
        pop: { '0%': { transform: 'scale(0.6)' }, '60%': { transform: 'scale(1.15)' }, '100%': { transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-400px 0' }, to: { backgroundPosition: '400px 0' } },
        wiggle: { '0%,100%': { transform: 'rotate(-3deg)' }, '50%': { transform: 'rotate(3deg)' } },
        jelly: { '0%,100%': { transform: 'scale(1,1)' }, '30%': { transform: 'scale(1.12,0.9)' }, '50%': { transform: 'scale(0.92,1.08)' }, '70%': { transform: 'scale(1.04,0.97)' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        'bounce-in': { '0%': { opacity: 0, transform: 'scale(0.6) rotate(-6deg)' }, '60%': { opacity: 1, transform: 'scale(1.06) rotate(2deg)' }, '100%': { transform: 'scale(1) rotate(0)' } },
      },
      animation: {
        'fade-up': 'fade-up 0.35s ease-out both',
        pop: 'pop 0.3s ease-out',
        shimmer: 'shimmer 1.4s linear infinite',
        wiggle: 'wiggle 0.6s ease-in-out',
        jelly: 'jelly 0.6s ease-in-out',
        marquee: 'marquee 40s linear infinite',
        'bounce-in': 'bounce-in 0.55s cubic-bezier(.2,.9,.3,1.3) both',
      },
    },
  },
  plugins: [],
};
